from manim import *


# BACKGROUND_SETTINGS
BACKGROUND_COLOR = "#151a2C"

# BOX SETTINGS
TITLE_BOX_HEIGHT = 0.7
TITLE_BOX_WIDTH = config.frame_width - 0.5
TITLE_BOX_POSITION = UL

DEFAULT_BOX_WIDTH = TITLE_BOX_WIDTH
DEFAULT_BOX_HEIGHT = config.frame_height - TITLE_BOX_HEIGHT - 1

BOX_FILL_COLOR = "#262C3F"
BOX_FILL_OPACITY = 1
BOX_BUFF = 0.3
BOX_STROKE_OPACITY = 0
BOX_STROKE_WIDTH = 0
BOX_STROKE_COLOR = WHITE

# TEXT_SETTINGS
TEXT_COLOR = "#FEFEFE"

TITLE_TEXT_SIZE = 27

TEXT_SIZE = 23
MEDIUM_TEXT_SIZE = 19
SMALL_TEXT_SIZE = 15
VERY_SMALL_TEXT_SIZE = 12

TEX_SIZE = 30
MEDIUM_TEX_SIZE = 25
SMALL_TEX_SIZE = 20
VERY_SMALL_TEX_SIZE = 15

# LOGO SETTINGS
LOGO_BUFF = 0.3
